### ISSUE TITLE
Porting this over to webhooks instead of API due to my internal company policy -- guidance?

### ISSUE THREAD

**Issue by lastb0isct** [ont/slacker#11]
I have left everything pretty much the same, but if you can give some input on what I'm missing here?  Essentially I've removed the rules processing and all of the other config.yml options other than url, which is the webhook url.

I'm able to get to the end of the handler.py but it doesn't seem to be calling the def, as it's not printing the "sending to slack" text.  I know that the requests.post is correct, but not sure what I'm missing in the def.  Any help is appreciated!

Thanks!

https://github.com/lastb0isct/slacker/blob/master/handler.py

**Comment by ont** [comment]
Ensure that function
```py
    def handle_message(self, message):
        """ This method will be called by aiosmtpd server when new mail will
            arrived.
        """
```
is called. Add debug message at the very beginning of it.

Then you call `send_to_slack` on https://github.com/lastb0isct/slacker/blob/master/handler.py#L28:
```py
self.send_to_slack(self.extract_text(message), **options)
```

But now function accepts only regular args (not key-args as before):
```py
    def send_to_slack(self, text, url):
```
During call to this function there will be type error.

For example:
```py
def aaa(a, b):
    pass

options = {"option1": 1, "option2": 2}
aaa(1, **options)
```
```
python test.py
Traceback (most recent call last):
  File "/tmp/test.py", line 5, in <module>
    aaa(1, **options)
TypeError: aaa() got an unexpected keyword argument 'option1'
```

**Comment by lastb0isct** [comment]
Thanks for the pointers @ont ! It seems that def handle_message is not being called...nothing is being printed.  Any ideas on how to diagnose why it isn't being called?

**Comment by ont** [comment]
How do you send your emails to server? On which port it is listening?

**Comment by lastb0isct** [comment]
It is listening on the 8025 port and i'm sending via sendemail on OSX -- says it sends successfully...

**Comment by lastb0isct** [comment]
It doesn't even seem to be calling the handler.py at all, i've put in a print at the top of the handler.py and it doesnt' print it either...

```
CMD ["aiosmtpd", "-n", "-l", "0.0.0.0:8025", "-c", "handler.MessageHandler"]
```

I wonder if the handler.py isn't being copied over or something?  I'm just editing the handler.py and then doing a `docker build .` in the directory to create another image -- is that enough to pull the handler.py into it? Or do I need any arguments to build it again?

**Comment by ont** [comment]
The command `docker build .` will build unnamed image (you still can see it in `docker images` output). And probably you don't start it with `docker run ...` command which use concrete name of image. You should use `-t image_name` every time you build/rebuild image.

You can easily check which version of code is used just by doing `docker exec -ti your_container_name sh` and then just view it with `cat` or any editor inside running container.

**Comment by lastb0isct** [comment]
I've been running it with the image id that was generated, so it's always the latest build, i'll check on the actual container now

**Comment by lastb0isct** [comment]
So, interesting behavior -- To test this I have exposed another port within the docker image (8026).

Utilizing the default 8025 does not work, nothing is output to the logs on the docker containter (`docker logs slacker`) I then go into the container with exec and run the exact same command except changing the port(`aiosmtpd -n -l 0.0.0.0:8026 -c handler.MessageHandler`) and it actually outputs this when I send a message to it, though doesn't actually send the message (You can ignore the massive amounts of extra in here...i had extra "print" calls to debug what was working):

```
# aiosmtpd -n -l 0.0.0.0:8026 -c handler.MessageHandler
MessageHandler was called
/etc/slacker/config.yml
This is calling handle_message
{'from': '"test@user.com" <test@user.com>', 'to': '"user@user.com" <user@user.com>', 'subject': 'THIS IS SUBJECT', 'body': [<email.message.Message object at 0x7fb892b13128>]}
matched {'url': '}
sending to slack [<email.message.Message object at 0x7fb892b13128>]
printing emailtext:
{'email': '[<email.message.Message object at 0x7fb892b13128>]'}
```

So it seems that somehow the handler.py isn't being loaded by aiosmtpd upon starting of the container?  Where are the logs for the initial run of aiosmtpd being kept, I'd think that they would show in the `docker logs` but maybe there is a different location I should be checking to see if it is actually running?

**Comment by lastb0isct** [comment]
I found the issue -- I wasn't using the appropriate variable for my json variable! needed to have "text": in there instead of what I was using...that screwed it up.  Now I have to debug how to get the appropriate message across to Slack for myself, currently just getting some weird message on my end instead:

```
{'from': '"test@user.com" <test@user.com>', 'to': '"user@user.com" <user@user.com>', 'subject': 'THIS IS SUBJECT', 'body': [<email.message.Message object at 0x7f7b87a55198>]}
matched {'url': ''}
sending to slack [<email.message.Message object at 0x7f7b87a55198>]
```

**Comment by lastb0isct** [comment]
@ont -- can't for the life of me find out how to grab just the `from` & `subject` from the messages into the webhook...how do I grab just those values from the fields dictionary.

Sorry for bothering so much on this.

**Comment by ont** [comment]
If you see in code there is `extract_text` method:
```py
    def extract_text(self, message):
        fmt = self.config['default'].get('format', '%(body)s')
        body = message.get_payload()
        subject = message['Subject']
        return fmt % dict(body=body, subject=subject)
```
By default it uses `'%(body)s'` template. You can specify `format: '%(from)s %(subject)s %(body)s'` in you config and it will inject this fields into result message.

**Comment by lastb0isct** [comment]
Thanks for this -- when I put this in:`format: "subject: %(subject)s; from: %(from)s"  ## default slack message format`
it gives me a KeyError.  It is possibly because of this line, which requires the body to be in it? 
`return fmt % dict(body=body, subject=subject)`

This is the error:
```
raceback (most recent call last):
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 741, in _handle_client
    await method(arg)
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 1454, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 473, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/handlers.py", line 185, in handle_DATA
    self.handle_message(message)
  File "/usr/src/app/handler.py", line 30, in handle_message
    self.send_to_slack(self.extract_text(message), **options)
  File "/usr/src/app/handler.py", line 52, in extract_text
    return fmt % dict(body=body, subject=subject)
KeyError: 'from'
```

EDIT: Confirmed that removing "from" from the config.yml resolves this keyerror...so doesn't seem to be fixable from the config.yml as we're forcing the body to be used in the fmt variable, aren't we?

**Comment by ont** [comment]
Just adjust function code (key 'from' is missed in dictionary):
```py
    def extract_text(self, message):
        fmt = self.config['default'].get('format', '%(body)s')
        from_ = message['From']
        body = message.get_payload()
        subject = message['Subject']
        return fmt % dict(body=body, subject=subject, from=from_)
```
